version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0-jammy
    container_name: academic_deadline_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - academic_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Academic Deadline Tracker Application
  app:
    build: . # Assuming Dockerfile is in the current directory
    container_name: academic_deadline_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/test
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - academic_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health", "||" , "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  academic_network:
    driver: bridge
