---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: academic-deadline
---
# Mongo Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: academic-deadline
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: password123
---
# App Secret (sensitive info: passwords, session secret, Twilio tokens)
apiVersion: v1
kind: Secret
metadata:
  name: academic-deadline-secret
  namespace: academic-deadline
type: Opaque
stringData:
  EMAIL_USER: 2002ak2002@gmail.com
  EMAIL_PASS: "prgi uvhi dpri wlaz"
  SESSION_SECRET: a3b2f8d23c84c5eaf8dca92b21a1c9d739e24c88b9db19e88b0d4f5e7e1c6f9d
  TWILIO_ACCOUNT_SID: ACee47a780e6b96d14076c87aa3fdaab64
  TWILIO_AUTH_TOKEN: 98546b7edc5e97bc0f9a8d93c14dae57
  TWILIO_PHONE_NUMBER: "+18788812691"
---
# App ConfigMap (non-sensitive values)
apiVersion: v1
kind: ConfigMap
metadata:
  name: academic-deadline-config
  namespace: academic-deadline
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGO_URI: "mongodb://mongodb:27017/test"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: academic-deadline
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0-jammy
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          hostPath:
            path: /var/lib/mongodb
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: academic-deadline
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academic-deadline-app
  namespace: academic-deadline
  labels:
    app: academic-deadline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: academic-deadline-app
  template:
    metadata:
      labels:
        app: academic-deadline-app
    spec:
      containers:
        - name: academic-deadline-app
          image: academic-deadline-app:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: academic-deadline-config
            - secretRef:
                name: academic-deadline-secret
---
# App Service
apiVersion: v1
kind: Service
metadata:
  name: academic-deadline-service
  namespace: academic-deadline
spec:
  type: LoadBalancer
  selector:
    app: academic-deadline-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
